Repository kids-first/kf-model-fhir, pull requests merged in 2020-06, with the labels that each got.

#155 🐛 Add missing pytest dep
  .circleci/config.yml
  dev-requirements.txt
Labels: bug

#157 🔥 Remove publish FHIR resources to Simplifier
  .circleci/config.yml
  README.md
Labels: refactor

#150 ✅ Integration tests
  .circleci/config.yml
  .gitignore
  README.md
  docs/data/ResearchStudy-sd-001.json
  docs/data/StructureDefinition-research-study.json
  kf_model_fhir/ingest_plugin/kids_first_fhir.py
  kf_model_fhir/ingest_plugin/resources/kfdrc_patient.py
  kf_model_fhir/ingest_plugin/shared.py
  requirements.txt
  scripts/integration_test.sh
  tests/conftest.py
  tests/data/examples/invalid/Patient-pt-001.json
  tests/data/examples/valid/Patient-pt-001.json
  tests/data/extensions/valid/StructureDefinition-proband-status.json
  tests/data/profiles/invalid/StructureDefinition-Participant.json
  tests/data/profiles/valid/StructureDefinition-participant.json
  tests/data/site_root/.gitignore
  tests/data/site_root/ig.ini
  tests/data/site_root/input/ImplementationGuide-KidsFirst.json
  tests/data/site_root/input/ignoreWarnings.txt
  tests/data/site_root/input/includes/menu.xml
  tests/data/site_root/input/pages/index.md
  tests/data/site_root/input/resources/examples/README.md
  tests/data/site_root/input/resources/extensions/README.md
  tests/data/site_root/input/resources/profiles/README.md
  tests/data/site_root/input/resources/search/README.md
  tests/data/site_root/input/resources/terminology/README.md
  tests/data/site_root/package-list.json
  tests/data/site_root/package.json
  tests/data/study_df.tsv
  tests/test_app.py
Labels: devops

#161 👷 Add project release workflow
  .github/prepare_assets.sh
  .github/release_assets.txt
  .github/workflows/gh_release.yml
  kf_model_fhir/__init__.py
  release_maker_cfg.json
  setup.py
Labels: devops, feature
