Repository kids-first/kf-model-fhir, pull requests merged in 2020-04, with the labels that each got.

#111 ✨ Small validation and error logging improvements
  kf_model_fhir/app.py
  tests/conftest.py
  tests/test_app.py
Labels: enhancement, feature

#112 ♻️ Add command includes custom validation
  kf_model_fhir/app.py
  tests/conftest.py
  tests/test_app.py
Labels: refactor

#115 🐛 Remove old state in IG on update
  README.md
  kf_model_fhir/app.py
  kf_model_fhir/loader.py
  tests/conftest.py
  tests/test_app.py
Labels: bug

#93 ✨ Initial Participant Conformance Resources
  .gitignore
  site_root/input/ImplementationGuide-KidsFirst.json
  site_root/input/resources/examples/Patient-pt-001.json
  site_root/input/resources/extensions/StructureDefinition-species.json
  site_root/input/resources/extensions/StructureDefinition-us-core-ethnicity.json
  site_root/input/resources/extensions/StructureDefinition-us-core-race.json
  site_root/input/resources/profiles/StructureDefinition-participant.json
  site_root/input/resources/search/SearchParameter-species.json
  site_root/input/resources/search/SearchParameter-us-core-ethnicity.json
  site_root/input/resources/search/SearchParameter-us-core-race.json
  site_root/input/resources/terminology/CodeSystem-cdcrec.json
  site_root/input/resources/terminology/CodeSystem-species.json
  site_root/input/resources/terminology/ValueSet-detailed-ethnicity.json
  site_root/input/resources/terminology/ValueSet-detailed-race.json
  site_root/input/resources/terminology/ValueSet-omb-ethnicity-category.json
  site_root/input/resources/terminology/ValueSet-omb-race-category.json
  site_root/input/resources/terminology/ValueSet-species.json
Labels: feature

#95 ✨ Initial Biospecimen Conformance Resources
  site_root/input/ImplementationGuide-KidsFirst.json
  site_root/input/resources/examples/Specimen-bs-001.json
  site_root/input/resources/extensions/StructureDefinition-concentration.json
  site_root/input/resources/profiles/StructureDefinition-biospecimen.json
  site_root/input/resources/search/SearchParameter-concentration.json
Labels: feature

#129 📝 Update README and Naming Conv docs
  README.md
  docs/naming_conventions.md
Labels: documentation

#99 ✨ Add KF DRC Patient mapper
  kf_model_fhir/mappers/README.md
  kf_model_fhir/mappers/common/utils.py
  kf_model_fhir/mappers/loader.py
  kf_model_fhir/mappers/resources/kfdrc_condition.py
  kf_model_fhir/mappers/resources/kfdrc_patient.py
Labels: feature

#101 ✨ Add KF DRC Specimen Mapper
  kf_model_fhir/mappers/README.md
  kf_model_fhir/mappers/loader.py
  kf_model_fhir/mappers/resources/kfdrc_specimen.py
Labels: feature

#102 ✨ Add KF DRC phenotype Mapper
  kf_model_fhir/mappers/README.md
  kf_model_fhir/mappers/loader.py
  kf_model_fhir/mappers/resources/kfdrc_condition.py
  kf_model_fhir/mappers/resources/kfdrc_phenotype.py
Labels: feature

#117 📝 Add release spec
  docs/images/npm.png
  docs/images/release.png
  docs/images/semvar.png
  docs/release.md
Labels: documentation

#132 ♻️ Use indent=2 to write IG json
  kf_model_fhir/app.py
Labels: refactor

#124 ✨Initial vital status conformance resources
  site_root/input/ImplementationGuide-KidsFirst.json
  site_root/input/resources/examples/Observation-vs-001-no-phi.json
  site_root/input/resources/examples/Observation-vs-001.json
  site_root/input/resources/profiles/StructureDefinition-kfdrc-vital-status-no-phi.json
  site_root/input/resources/profiles/StructureDefinition-kfdrc-vital-status.json
Labels: feature
