Repository kids-first/kf-model-fhir, pull requests merged in 2020-03, with the labels that each got.

#83 ✨ Add script for making HPO CodeSystem
  scripts/hpo_codesystem.py
Labels: feature

#85 🔧 Resolve IG Validation Errors
  site_root/source/examples/individual-example.json
  tests/data/resources/valid/participant-example.json
Labels: feature

#86 ♻️ Replace Phenopackets resources w/ KF resources
  site_root/ig.json
  site_root/source/examples/individual-example.json
  site_root/source/examples/participant-example.json
  site_root/source/pages/_includes/Individual-intro.md
  site_root/source/pages/_includes/Individual-search.md
  site_root/source/pages/_includes/Individual-summary.md
  site_root/source/pages/_includes/Participant-intro.md
  site_root/source/pages/_includes/Participant-search.md
  site_root/source/pages/_includes/Participant-summary.md
  site_root/source/resources/CodeSystem-karyotypic-sex.json
  site_root/source/resources/StructureDefinition-Individual.json
  site_root/source/resources/StructureDefinition-Participant.json
  site_root/source/resources/StructureDefinition-individual-karyotypic-sex.json
  site_root/source/resources/ValueSet-karyotypic-sex.json
  site_root/source/resources/implementationguide/kidsfirst.json
Labels: refactor

#91 🐛 Resolve name conflicts w/generated IG output files
  kf_model_fhir/app.py
Labels: bug

#94 📝 Spec for FHIR model naming conventions
  docs/naming_conventions.md
Labels: documentation
