Repository kids-first/kf-model-fhir, pull requests merged in 2020-05, with the labels that each got.

#134 🚧 implement vital-status mapper
  kf_model_fhir/mappers/README.md
  kf_model_fhir/mappers/loader.py
  kf_model_fhir/mappers/resources/kfdrc_patient.py
  kf_model_fhir/mappers/resources/kfdrc_vital_status.py
Labels: feature

#139 🐛 Only publish to simplifier on merge to master
  .circleci/config.yml
Labels: bug

#140 🔥 Replace fhirmodel CLI src with ncpi-fhir-utility
  .circleci/config.yml
  README.md
  kf_model_fhir/app.py
  kf_model_fhir/cli.py
  kf_model_fhir/client.py
  kf_model_fhir/config.py
  kf_model_fhir/loader.py
  kf_model_fhir/mappers/loader.py
  kf_model_fhir/utils.py
  requirements.txt
  scripts/build.sh
  scripts/run_publisher.sh
  setup.py
  tests/test_app.py
Labels: refactor

#137 ✨ Initial investigator/study conformance resources/mappers
  kf_model_fhir/mappers/README.md
  kf_model_fhir/mappers/loader.py
  kf_model_fhir/mappers/resources/kfdrc_condition.py
  kf_model_fhir/mappers/resources/kfdrc_patient.py
  kf_model_fhir/mappers/resources/kfdrc_phenotype.py
  kf_model_fhir/mappers/resources/kfdrc_research_study.py
  kf_model_fhir/mappers/resources/kfdrc_specimen.py
  kf_model_fhir/mappers/resources/organization.py
  kf_model_fhir/mappers/resources/practitioner.py
  kf_model_fhir/mappers/resources/practitioner_role.py
  site_root/input/ImplementationGuide-KidsFirst.json
  site_root/input/resources/examples/Organization-og-001.json
  site_root/input/resources/examples/Practitioner-ig-001.json
  site_root/input/resources/examples/PractitionerRole-pr-001.json
  site_root/input/resources/examples/ResearchStudy-sd-001.json
  site_root/input/resources/extensions/StructureDefinition-display-name.json
  site_root/input/resources/extensions/StructureDefinition-related-organization.json
  site_root/input/resources/profiles/StructureDefinition-kfdrc-research-study.json
  site_root/input/resources/search/SearchParameter-display-name.json
  site_root/input/resources/search/SearchParameter-related-organization-role.json
  site_root/input/resources/search/SearchParameter-related-organization.json
Labels: feature

#152 🚧 remove unused resource
  site_root/input/ImplementationGuide-KidsFirst.json
  site_root/input/ignoreWarnings.txt
  tests/data/site_root/input/ignoreWarnings.txt
Labels: bug, refactor
