Repository kids-first/kf-model-fhir, pull requests merged in 2020-07, with the labels that each got.

#136 ✨ New ingest plugin for FHIR
  dev-requirements.txt
  kf_model_fhir/ingest_plugin/README.md
  kf_model_fhir/ingest_plugin/app_settings.py
  kf_model_fhir/ingest_plugin/kids_first_fhir.py
  kf_model_fhir/ingest_plugin/shared.py
  kf_model_fhir/ingest_plugin/target_api_builders/__init__.py
  kf_model_fhir/ingest_plugin/target_api_builders/group.py
  kf_model_fhir/ingest_plugin/target_api_builders/kfdrc_condition.py
  kf_model_fhir/ingest_plugin/target_api_builders/kfdrc_patient.py
  kf_model_fhir/ingest_plugin/target_api_builders/kfdrc_patient_relations.py
  kf_model_fhir/ingest_plugin/target_api_builders/kfdrc_phenotype.py
  kf_model_fhir/ingest_plugin/target_api_builders/kfdrc_research_study.py
  kf_model_fhir/ingest_plugin/target_api_builders/kfdrc_specimen.py
  kf_model_fhir/ingest_plugin/target_api_builders/kfdrc_vital_status.py
  kf_model_fhir/ingest_plugin/target_api_builders/organization.py
  kf_model_fhir/ingest_plugin/target_api_builders/practitioner.py
  kf_model_fhir/ingest_plugin/target_api_builders/practitioner_role.py
  kf_model_fhir/mappers/common/utils.py
  kf_model_fhir/mappers/loader.py
  kf_model_fhir/mappers/resources/group.py
  kf_model_fhir/mappers/resources/kfdrc_condition.py
  kf_model_fhir/mappers/resources/kfdrc_patient.py
  kf_model_fhir/mappers/resources/kfdrc_patient_relations.py
  kf_model_fhir/mappers/resources/kfdrc_phenotype.py
  kf_model_fhir/mappers/resources/kfdrc_research_study.py
  kf_model_fhir/mappers/resources/kfdrc_vital_status.py
  kf_model_fhir/mappers/resources/organization.py
  kf_model_fhir/mappers/resources/practitioner.py
  kf_model_fhir/mappers/resources/practitioner_role.py
  requirements.txt
  site_root/input/resources/examples/Condition-cd-001-no-phi.json
  site_root/input/resources/examples/Condition-cd-001.json
  tests/conftest.py
  tests/data/default.tsv
  tests/data/family_relationships.tsv
  tests/data/study_df.tsv
  tests/test_app.py
Labels: feature

#167 🏷 Release 0.1.0
  CHANGELOG.md
  site_root/ig.ini
  site_root/input/ImplementationGuide-KidsFirst.json
  site_root/input/resources/examples/Condition-cd-001-no-phi.json
  site_root/input/resources/examples/Condition-cd-001.json
  site_root/input/resources/examples/Observation-ph-001-no-phi.json
  site_root/input/resources/examples/Observation-ph-001.json
  site_root/input/resources/examples/Observation-vs-001-no-phi.json
  site_root/input/resources/examples/Observation-vs-001.json
  site_root/input/resources/examples/Patient-pt-001-no-phi.json
  site_root/input/resources/examples/Patient-pt-001.json
  site_root/input/resources/examples/Patient-pt-002.json
  site_root/input/resources/examples/Patient-pt-003.json
  site_root/input/resources/examples/ResearchStudy-sd-001.json
  site_root/input/resources/examples/Specimen-bs-001-no-phi.json
  site_root/input/resources/examples/Specimen-bs-001.json
  site_root/input/resources/extensions/StructureDefinition-age-at-event.json
  site_root/input/resources/extensions/StructureDefinition-concentration.json
  site_root/input/resources/extensions/StructureDefinition-display-name.json
  site_root/input/resources/extensions/StructureDefinition-related-organization.json
  site_root/input/resources/extensions/StructureDefinition-relation.json
  site_root/input/resources/extensions/StructureDefinition-species.json
  site_root/input/resources/profiles/StructureDefinition-kfdrc-condition-no-phi.json
  site_root/input/resources/profiles/StructureDefinition-kfdrc-condition.json
  site_root/input/resources/profiles/StructureDefinition-kfdrc-patient-no-phi.json
  site_root/input/resources/profiles/StructureDefinition-kfdrc-patient.json
  site_root/input/resources/profiles/StructureDefinition-kfdrc-phenotype-no-phi.json
  site_root/input/resources/profiles/StructureDefinition-kfdrc-phenotype.json
  site_root/input/resources/profiles/StructureDefinition-kfdrc-research-study.json
  site_root/input/resources/profiles/StructureDefinition-kfdrc-specimen-no-phi.json
  site_root/input/resources/profiles/StructureDefinition-kfdrc-specimen.json
  site_root/input/resources/profiles/StructureDefinition-kfdrc-vital-status-no-phi.json
  site_root/input/resources/profiles/StructureDefinition-kfdrc-vital-status.json
  site_root/input/resources/search/SearchParameter-age-at-event.json
  site_root/input/resources/search/SearchParameter-concentration.json
  site_root/input/resources/search/SearchParameter-display-name.json
  site_root/input/resources/search/SearchParameter-related-organization-role.json
  site_root/input/resources/search/SearchParameter-related-organization.json
  site_root/input/resources/search/SearchParameter-relation-note.json
  site_root/input/resources/search/SearchParameter-relation-subject.json
  site_root/input/resources/search/SearchParameter-relation.json
  site_root/input/resources/search/SearchParameter-species.json
  site_root/input/resources/terminology/CodeSystem-species.json
  site_root/input/resources/terminology/ValueSet-phenotype-codes.json
  site_root/input/resources/terminology/ValueSet-species.json
  site_root/package.json
Labels: release

#169 🏷 Release 0.1.1
  CHANGELOG.md
  site_root/ig.ini
  site_root/input/ImplementationGuide-KidsFirst.json
  site_root/input/resources/examples/Condition-cd-001-no-phi.json
  site_root/input/resources/examples/Condition-cd-001.json
  site_root/input/resources/examples/Observation-ph-001-no-phi.json
  site_root/input/resources/examples/Observation-ph-001.json
  site_root/input/resources/examples/Observation-vs-001-no-phi.json
  site_root/input/resources/examples/Observation-vs-001.json
  site_root/input/resources/examples/Patient-pt-001-no-phi.json
  site_root/input/resources/examples/Patient-pt-001.json
  site_root/input/resources/examples/Patient-pt-002.json
  site_root/input/resources/examples/Patient-pt-003.json
  site_root/input/resources/examples/ResearchStudy-sd-001.json
  site_root/input/resources/examples/Specimen-bs-001-no-phi.json
  site_root/input/resources/examples/Specimen-bs-001.json
  site_root/input/resources/extensions/StructureDefinition-age-at-event.json
  site_root/input/resources/extensions/StructureDefinition-concentration.json
  site_root/input/resources/extensions/StructureDefinition-display-name.json
  site_root/input/resources/extensions/StructureDefinition-related-organization.json
  site_root/input/resources/extensions/StructureDefinition-relation.json
  site_root/input/resources/extensions/StructureDefinition-species.json
  site_root/input/resources/profiles/StructureDefinition-kfdrc-condition-no-phi.json
  site_root/input/resources/profiles/StructureDefinition-kfdrc-condition.json
  site_root/input/resources/profiles/StructureDefinition-kfdrc-patient-no-phi.json
  site_root/input/resources/profiles/StructureDefinition-kfdrc-patient.json
  site_root/input/resources/profiles/StructureDefinition-kfdrc-phenotype-no-phi.json
  site_root/input/resources/profiles/StructureDefinition-kfdrc-phenotype.json
  site_root/input/resources/profiles/StructureDefinition-kfdrc-research-study.json
  site_root/input/resources/profiles/StructureDefinition-kfdrc-specimen-no-phi.json
  site_root/input/resources/profiles/StructureDefinition-kfdrc-specimen.json
  site_root/input/resources/profiles/StructureDefinition-kfdrc-vital-status-no-phi.json
  site_root/input/resources/profiles/StructureDefinition-kfdrc-vital-status.json
  site_root/input/resources/search/SearchParameter-age-at-event.json
  site_root/input/resources/search/SearchParameter-concentration.json
  site_root/input/resources/search/SearchParameter-display-name.json
  site_root/input/resources/search/SearchParameter-related-organization-role.json
  site_root/input/resources/search/SearchParameter-related-organization.json
  site_root/input/resources/search/SearchParameter-relation-note.json
  site_root/input/resources/search/SearchParameter-relation-subject.json
  site_root/input/resources/search/SearchParameter-relation.json
  site_root/input/resources/search/SearchParameter-species.json
  site_root/input/resources/terminology/CodeSystem-species.json
  site_root/input/resources/terminology/ValueSet-phenotype-codes.json
  site_root/input/resources/terminology/ValueSet-species.json
  site_root/package.json
Labels: release

#171 🏷 Release 0.1.2
  CHANGELOG.md
  site_root/ig.ini
  site_root/input/ImplementationGuide-KidsFirst.json
  site_root/input/resources/examples/Condition-cd-001-no-phi.json
  site_root/input/resources/examples/Condition-cd-001.json
  site_root/input/resources/examples/Observation-ph-001-no-phi.json
  site_root/input/resources/examples/Observation-ph-001.json
  site_root/input/resources/examples/Observation-vs-001-no-phi.json
  site_root/input/resources/examples/Observation-vs-001.json
  site_root/input/resources/examples/Patient-pt-001-no-phi.json
  site_root/input/resources/examples/Patient-pt-001.json
  site_root/input/resources/examples/Patient-pt-002.json
  site_root/input/resources/examples/Patient-pt-003.json
  site_root/input/resources/examples/ResearchStudy-sd-001.json
  site_root/input/resources/examples/Specimen-bs-001-no-phi.json
  site_root/input/resources/examples/Specimen-bs-001.json
  site_root/input/resources/extensions/StructureDefinition-age-at-event.json
  site_root/input/resources/extensions/StructureDefinition-concentration.json
  site_root/input/resources/extensions/StructureDefinition-display-name.json
  site_root/input/resources/extensions/StructureDefinition-related-organization.json
  site_root/input/resources/extensions/StructureDefinition-relation.json
  site_root/input/resources/extensions/StructureDefinition-species.json
  site_root/input/resources/profiles/StructureDefinition-kfdrc-condition-no-phi.json
  site_root/input/resources/profiles/StructureDefinition-kfdrc-condition.json
  site_root/input/resources/profiles/StructureDefinition-kfdrc-patient-no-phi.json
  site_root/input/resources/profiles/StructureDefinition-kfdrc-patient.json
  site_root/input/resources/profiles/StructureDefinition-kfdrc-phenotype-no-phi.json
  site_root/input/resources/profiles/StructureDefinition-kfdrc-phenotype.json
  site_root/input/resources/profiles/StructureDefinition-kfdrc-research-study.json
  site_root/input/resources/profiles/StructureDefinition-kfdrc-specimen-no-phi.json
  site_root/input/resources/profiles/StructureDefinition-kfdrc-specimen.json
  site_root/input/resources/profiles/StructureDefinition-kfdrc-vital-status-no-phi.json
  site_root/input/resources/profiles/StructureDefinition-kfdrc-vital-status.json
  site_root/input/resources/search/SearchParameter-age-at-event.json
  site_root/input/resources/search/SearchParameter-concentration.json
  site_root/input/resources/search/SearchParameter-display-name.json
  site_root/input/resources/search/SearchParameter-related-organization-role.json
  site_root/input/resources/search/SearchParameter-related-organization.json
  site_root/input/resources/search/SearchParameter-relation-note.json
  site_root/input/resources/search/SearchParameter-relation-subject.json
  site_root/input/resources/search/SearchParameter-relation.json
  site_root/input/resources/search/SearchParameter-species.json
  site_root/input/resources/terminology/CodeSystem-species.json
  site_root/input/resources/terminology/ValueSet-phenotype-codes.json
  site_root/input/resources/terminology/ValueSet-species.json
  site_root/package.json
Labels: release

#173 🏷 Release 0.1.3
  CHANGELOG.md
  site_root/ig.ini
  site_root/input/ImplementationGuide-KidsFirst.json
  site_root/input/resources/examples/Condition-cd-001-no-phi.json
  site_root/input/resources/examples/Condition-cd-001.json
  site_root/input/resources/examples/Observation-ph-001-no-phi.json
  site_root/input/resources/examples/Observation-ph-001.json
  site_root/input/resources/examples/Observation-vs-001-no-phi.json
  site_root/input/resources/examples/Observation-vs-001.json
  site_root/input/resources/examples/Patient-pt-001-no-phi.json
  site_root/input/resources/examples/Patient-pt-001.json
  site_root/input/resources/examples/Patient-pt-002.json
  site_root/input/resources/examples/Patient-pt-003.json
  site_root/input/resources/examples/ResearchStudy-sd-001.json
  site_root/input/resources/examples/Specimen-bs-001-no-phi.json
  site_root/input/resources/examples/Specimen-bs-001.json
  site_root/input/resources/extensions/StructureDefinition-age-at-event.json
  site_root/input/resources/extensions/StructureDefinition-concentration.json
  site_root/input/resources/extensions/StructureDefinition-display-name.json
  site_root/input/resources/extensions/StructureDefinition-related-organization.json
  site_root/input/resources/extensions/StructureDefinition-relation.json
  site_root/input/resources/extensions/StructureDefinition-species.json
  site_root/input/resources/profiles/StructureDefinition-kfdrc-condition-no-phi.json
  site_root/input/resources/profiles/StructureDefinition-kfdrc-condition.json
  site_root/input/resources/profiles/StructureDefinition-kfdrc-patient-no-phi.json
  site_root/input/resources/profiles/StructureDefinition-kfdrc-patient.json
  site_root/input/resources/profiles/StructureDefinition-kfdrc-phenotype-no-phi.json
  site_root/input/resources/profiles/StructureDefinition-kfdrc-phenotype.json
  site_root/input/resources/profiles/StructureDefinition-kfdrc-research-study.json
  site_root/input/resources/profiles/StructureDefinition-kfdrc-specimen-no-phi.json
  site_root/input/resources/profiles/StructureDefinition-kfdrc-specimen.json
  site_root/input/resources/profiles/StructureDefinition-kfdrc-vital-status-no-phi.json
  site_root/input/resources/profiles/StructureDefinition-kfdrc-vital-status.json
  site_root/input/resources/search/SearchParameter-age-at-event.json
  site_root/input/resources/search/SearchParameter-concentration.json
  site_root/input/resources/search/SearchParameter-display-name.json
  site_root/input/resources/search/SearchParameter-related-organization-role.json
  site_root/input/resources/search/SearchParameter-related-organization.json
  site_root/input/resources/search/SearchParameter-relation-note.json
  site_root/input/resources/search/SearchParameter-relation-subject.json
  site_root/input/resources/search/SearchParameter-relation.json
  site_root/input/resources/search/SearchParameter-species.json
  site_root/input/resources/terminology/CodeSystem-species.json
  site_root/input/resources/terminology/ValueSet-phenotype-codes.json
  site_root/input/resources/terminology/ValueSet-species.json
  site_root/package.json
Labels: release

#159 👷 Add FHIR model deploy pipeline
  .dockerignore
  Jenkinsfile
  scripts/integration_test.sh
  scripts/jenkins/Dockerfile
  scripts/jenkins/deploy.sh
  scripts/jenkins/entrypoint.sh
  scripts/jenkins/test.sh
Labels: devops

#181 🏷 Release 0.1.0
  CHANGELOG.md
  site_root/ig.ini
  site_root/input/ImplementationGuide-KidsFirst.json
  site_root/input/resources/examples/Condition-cd-001-no-phi.json
  site_root/input/resources/examples/Condition-cd-001.json
  site_root/input/resources/examples/Observation-ph-001-no-phi.json
  site_root/input/resources/examples/Observation-ph-001.json
  site_root/input/resources/examples/Observation-vs-001-no-phi.json
  site_root/input/resources/examples/Observation-vs-001.json
  site_root/input/resources/examples/Patient-pt-001-no-phi.json
  site_root/input/resources/examples/Patient-pt-001.json
  site_root/input/resources/examples/Patient-pt-002.json
  site_root/input/resources/examples/Patient-pt-003.json
  site_root/input/resources/examples/ResearchStudy-sd-001.json
  site_root/input/resources/examples/Specimen-bs-001-no-phi.json
  site_root/input/resources/examples/Specimen-bs-001.json
  site_root/input/resources/extensions/StructureDefinition-age-at-event.json
  site_root/input/resources/extensions/StructureDefinition-concentration.json
  site_root/input/resources/extensions/StructureDefinition-display-name.json
  site_root/input/resources/extensions/StructureDefinition-related-organization.json
  site_root/input/resources/extensions/StructureDefinition-relation.json
  site_root/input/resources/extensions/StructureDefinition-species.json
  site_root/input/resources/profiles/StructureDefinition-kfdrc-condition-no-phi.json
  site_root/input/resources/profiles/StructureDefinition-kfdrc-condition.json
  site_root/input/resources/profiles/StructureDefinition-kfdrc-patient-no-phi.json
  site_root/input/resources/profiles/StructureDefinition-kfdrc-patient.json
  site_root/input/resources/profiles/StructureDefinition-kfdrc-phenotype-no-phi.json
  site_root/input/resources/profiles/StructureDefinition-kfdrc-phenotype.json
  site_root/input/resources/profiles/StructureDefinition-kfdrc-research-study.json
  site_root/input/resources/profiles/StructureDefinition-kfdrc-specimen-no-phi.json
  site_root/input/resources/profiles/StructureDefinition-kfdrc-specimen.json
  site_root/input/resources/profiles/StructureDefinition-kfdrc-vital-status-no-phi.json
  site_root/input/resources/profiles/StructureDefinition-kfdrc-vital-status.json
  site_root/input/resources/search/SearchParameter-age-at-event.json
  site_root/input/resources/search/SearchParameter-concentration.json
  site_root/input/resources/search/SearchParameter-display-name.json
  site_root/input/resources/search/SearchParameter-related-organization-role.json
  site_root/input/resources/search/SearchParameter-related-organization.json
  site_root/input/resources/search/SearchParameter-relation-note.json
  site_root/input/resources/search/SearchParameter-relation-subject.json
  site_root/input/resources/search/SearchParameter-relation.json
  site_root/input/resources/search/SearchParameter-species.json
  site_root/input/resources/terminology/CodeSystem-species.json
  site_root/input/resources/terminology/ValueSet-phenotype-codes.json
  site_root/input/resources/terminology/ValueSet-species.json
  site_root/package.json
Labels: release
